### ISSUE TITLE
I want to teach a Forwards workshop - where to start?

### ISSUE THREAD

**Issue by angela-li** [forwards/workshops#2]
Are there any materials for onboarding new instructors of Forwards workshops? I would love to teach one in Chicago. For now, I was just thinking of using some of the materials and walking through that. Is there a system set up to onboard teachers?

**Comment by hturner** [comment]
Excellent to hear that you would like to teach a Forwards workshop. Is it the package development workshop you are interested in, or the one for high school girls?

Running a package development workshop for women in the US is one of the goals of our R Consortium funded project, so it may be possible to for you to be involved in an "official" workshop, with some associated funding.

The idea was that we would run a few official workshops, to test and polish the materials, then they would be available for anyone to use in a self-organised way. But we could think about more support for on-boarding; one idea was to add teacher notes to go along with the slides. Contributions to this side of things would also be welcome!

**Comment by angela-li** [comment]
I'm interested in the package development workshop for women here in Chicago, so being involved in an "official" workshop with funding in the US sounds great! And I can give feedback on the materials as well when I teach them. Should I send someone an email?

I would also be interested in adding teacher notes and helping to onboard additional teachers in the future, and could help with that after teaching a workshop myself! I think it would be great to tie this in with the R-Ladies community (I'm the founder of the Chicago group), so that Meetup leaders like me could feel empowered to lead package development workshops.

**Comment by hturner** [comment]
We are having a slackathon this weekend so I will let the teaching team know and we can follow up after that. Do you have any particular time in period in mind?

**Comment by angela-li** [comment]
Great! I think we're aiming for early March, so we can get space and such. I'm currently doing a lot of teaching for my job (and am doing some Software Carpentry stuff too) so I would love to do this.

**Comment by dicook** [comment]
Hi Angela,

This is terrific! There is also funding that can be used to pay for lunches and break food available. 

I am happy to help you get you head around materials too.

cheers,
Di

**Comment by jtr13** [comment]
Happy to chat and share what worked for us in New York.

**Comment by angela-li** [comment]
How should I go about getting funding and such? Perhaps we should move this conversation to email?

**Comment by dicook** [comment]
Hi Angela,

It might be best to use the forwards slack channel for the discussion. You
will find a lot of the info you need already there. It it is ok with
Heather, I can add you to that channel.

cheers,
Di

**Comment by dicook** [comment]
could you email me visnut@gmail.com your email address? so that I can add
you to the slack group?
