### ISSUE TITLE
draft of learning objectives added for Package documentation workshop (workshop 4)

### ISSUE THREAD

**Issue by 3mmaRand** [forwards/workshops#34]
workshops/package-dev-modules/overview.md
Hi @mine-cetinkaya-rundel I tried drafting some LO for the 4th workshop but please do alter or edit as you think best. Be good to get the event on eventbrite this week

**Comment by mine-cetinkaya-rundel** [comment]
Missed this here but will note from our Slack conversation for the record -- we agreed to also add a little bit on package websites with pkgdown.
