### ISSUE TITLE
Standardize workshop pre/post surveys

### ISSUE THREAD

**Issue by angela-li** [forwards/workshops#8]
We did this for the Chicago workshop, and it helped us get a sense of how effective the workshop was. It would be good to include a standard set of questions in here (or perhaps the surveys folder) so that others could design these surveys.

**Comment by hturner** [comment]
We now have a LimeSurvey instance funded by the R Foundation. This would allow us to create a survey template that people can import into a free LimeSurvey instance, which is good for 25 responses, or a professional LimeSurvey if they have access to that. I think the R Foundation one would be available for R Foundation supported events, e.g. workshops run by Forwards memebrs , or workshops at R Foundation endorsed conferences.

**Comment by hturner** [comment]
@3mmaRand can you export the surveys from LimeSurvey in various forms so that people could import them into LimeSurvey/use a reference when creating their own forms?

**Comment by 3mmaRand** [comment]
Here they are. There are 4 surveys: Workshop application, Workshop scholarship application, preworkshop learning survey and post workshop learning survey

[rforwards.zip](https://github.com/forwards/workshops/files/3505541/rforwards.zip)

**Comment by hturner** [comment]
Righto - can you put these in a folder in the workshops repo?

**Comment by 3mmaRand** [comment]
I think this is done. Standardised surveys are on limesurvey
